In [ ]:
# Bubble

def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr [j+1] = arr[j+1], arr[j]
    return arr

# Contoh
data = [64, 34, 25, 12, 22, 11, 90]
sorted_data = bubble_sort(data)
print("Data yang telah diurutkan:", sorted_data)

Data yang telah diurutkan: [11, 12, 22, 25, 34, 64, 90]

In [ ]:
# Select

def selection_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr

#Contoh
data = [64, 34, 25, 12, 22, 11, 90, 1]
sorted_data = selection_sort(data)
print("Data yang telah diurutkan:", sorted_data)

Data yang telah diurutkan: [1, 11, 12, 22, 25, 34, 64, 90]

In [ ]:
# Insertion

def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
            arr[j + 1] = key
    return arr

# Contoh
data = [64, 34, 25, 12, 22, 11, 90]
sorted_data = insertion_sort(data)
print("Data yang telah diurutkan:", sorted_data)

Data yang telah diurutkan: [11, 12, 22, 25, 34, 64, 90]

In [ ]:
# Quick

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

# Contoh
data = [64, 34, 25, 12, 22, 11, 90]
sorted_data = quick_sort(data)
print("Data yang telah diurutkan:", sorted_data)

Data yang telah diurutkan: [11, 12, 22, 25, 34, 64, 90]

In [3]:
import tabulate  # Untuk menampilkan output dalam bentuk tabel

# Data pelanggan dalam bentuk list of dictionaries
data_pelanggan = [
    {"nama": "Zahra", "umur": 25, "total_belanja": 1200000},
    {"nama": "Akmal", "umur": 31, "total_belanja": 850000},
    {"nama": "Salwa", "umur": 22, "total_belanja": 950000},
    {"nama": "Faiz", "umur": 27, "total_belanja": 1100000},
]

# Implementasi Quick Sort
def quick_sort(arr, key):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x[key] < pivot[key]]
    middle = [x for x in arr if x[key] == pivot[key]]
    right = [x for x in arr if x[key] > pivot[key]]
    return quick_sort(left, key) + middle + quick_sort(right, key)

# Fungsi untuk mencetak tabel
def print_table(data):
    headers = ["Nama", "Umur", "Total Belanja"]
    table_data = [[d["nama"], d["umur"], f"Rp {d['total_belanja']:,}"] for d in data]
    print(tabulate.tabulate(table_data, headers=headers, tablefmt="grid"))

# Pilihan sorting
print("Pilih metode pengurutan:")
print("1. Berdasarkan Nama (A-Z)")
print("2. Berdasarkan Umur (Termuda ke Tertua)")
print("3. Berdasarkan Total Belanja (Terkecil ke Terbesar)")

choice = int(input("Masukkan pilihan (1/2/3): "))

if choice == 1:
    sorted_data = quick_sort(data_pelanggan, "nama")
elif choice == 2:
    sorted_data = quick_sort(data_pelanggan, "umur")
elif choice == 3:
    sorted_data = quick_sort(data_pelanggan, "total_belanja")
else:
    print("Pilihan tidak valid!")
    exit()

# Menampilkan hasil dalam bentuk tabel
print("\nHasil Pengurutan:")
print_table(sorted_data)

Pilih metode pengurutan:
1. Berdasarkan Nama (A-Z)
2. Berdasarkan Umur (Termuda ke Tertua)
3. Berdasarkan Total Belanja (Terkecil ke Terbesar)
Masukkan pilihan (1/2/3): 3

Hasil Pengurutan:
+--------+--------+-----------------+
| Nama   |   Umur | Total Belanja   |
+========+========+=================+
| Akmal  |     31 | Rp 850,000      |
+--------+--------+-----------------+
| Salwa  |     22 | Rp 950,000      |
+--------+--------+-----------------+
| Faiz   |     27 | Rp 1,100,000    |
+--------+--------+-----------------+
| Zahra  |     25 | Rp 1,200,000    |
+--------+--------+-----------------+